/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.railstream.libraries.schemas.in;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Schema for temperature sensor readings */
@org.apache.avro.specific.AvroGenerated
public class SensorData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2990186924713326580L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorData\",\"namespace\":\"com.railstream.libraries.schemas\",\"doc\":\"Schema for temperature sensor readings\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"string\",\"doc\":\"Unique identifier of the sensor\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Epoch time in milliseconds (UTC)\"},{\"name\":\"temperature\",\"type\":\"double\",\"doc\":\"Recorded temperature\"},{\"name\":\"unit\",\"type\":\"string\",\"doc\":\"Unit of measurement (e.g., Celsius)\"},{\"name\":\"location\",\"type\":[\"null\",\"string\"],\"doc\":\"Sensor location metadata (name/code)\",\"default\":null},{\"name\":\"latitude\",\"type\":[\"null\",\"float\"],\"doc\":\"Geolocation latitude (if available)\",\"default\":null},{\"name\":\"longitude\",\"type\":[\"null\",\"float\"],\"doc\":\"Geolocation longitude (if available)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SensorData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensorData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensorData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensorData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensorData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensorData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensorData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensorData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SensorData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of the sensor */
  private java.lang.CharSequence sensor_id;
  /** Epoch time in milliseconds (UTC) */
  private long timestamp;
  /** Recorded temperature */
  private double temperature;
  /** Unit of measurement (e.g., Celsius) */
  private java.lang.CharSequence unit;
  /** Sensor location metadata (name/code) */
  private java.lang.CharSequence location;
  /** Geolocation latitude (if available) */
  private java.lang.Float latitude;
  /** Geolocation longitude (if available) */
  private java.lang.Float longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorData() {}

  /**
   * All-args constructor.
   * @param sensor_id Unique identifier of the sensor
   * @param timestamp Epoch time in milliseconds (UTC)
   * @param temperature Recorded temperature
   * @param unit Unit of measurement (e.g., Celsius)
   * @param location Sensor location metadata (name/code)
   * @param latitude Geolocation latitude (if available)
   * @param longitude Geolocation longitude (if available)
   */
  public SensorData(java.lang.CharSequence sensor_id, java.lang.Long timestamp, java.lang.Double temperature, java.lang.CharSequence unit, java.lang.CharSequence location, java.lang.Float latitude, java.lang.Float longitude) {
    this.sensor_id = sensor_id;
    this.timestamp = timestamp;
    this.temperature = temperature;
    this.unit = unit;
    this.location = location;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_id;
    case 1: return timestamp;
    case 2: return temperature;
    case 3: return unit;
    case 4: return location;
    case 5: return latitude;
    case 6: return longitude;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: temperature = (java.lang.Double)value$; break;
    case 3: unit = (java.lang.CharSequence)value$; break;
    case 4: location = (java.lang.CharSequence)value$; break;
    case 5: latitude = (java.lang.Float)value$; break;
    case 6: longitude = (java.lang.Float)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return Unique identifier of the sensor
   */
  public java.lang.CharSequence getSensorId() {
    return sensor_id;
  }


  /**
   * Sets the value of the 'sensor_id' field.
   * Unique identifier of the sensor
   * @param value the value to set.
   */
  public void setSensorId(java.lang.CharSequence value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Epoch time in milliseconds (UTC)
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Epoch time in milliseconds (UTC)
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return Recorded temperature
   */
  public double getTemperature() {
    return temperature;
  }


  /**
   * Sets the value of the 'temperature' field.
   * Recorded temperature
   * @param value the value to set.
   */
  public void setTemperature(double value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return Unit of measurement (e.g., Celsius)
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * Unit of measurement (e.g., Celsius)
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return Sensor location metadata (name/code)
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * Sensor location metadata (name/code)
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return Geolocation latitude (if available)
   */
  public java.lang.Float getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * Geolocation latitude (if available)
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Float value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return Geolocation longitude (if available)
   */
  public java.lang.Float getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * Geolocation longitude (if available)
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Float value) {
    this.longitude = value;
  }

  /**
   * Creates a new SensorData RecordBuilder.
   * @return A new SensorData RecordBuilder
   */
  public static SensorData.Builder newBuilder() {
    return new SensorData.Builder();
  }

  /**
   * Creates a new SensorData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorData RecordBuilder
   */
  public static SensorData.Builder newBuilder(SensorData.Builder other) {
    if (other == null) {
      return new SensorData.Builder();
    } else {
      return new SensorData.Builder(other);
    }
  }

  /**
   * Creates a new SensorData RecordBuilder by copying an existing SensorData instance.
   * @param other The existing instance to copy.
   * @return A new SensorData RecordBuilder
   */
  public static SensorData.Builder newBuilder(SensorData other) {
    if (other == null) {
      return new SensorData.Builder();
    } else {
      return new SensorData.Builder(other);
    }
  }

  /**
   * RecordBuilder for SensorData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorData>
    implements org.apache.avro.data.RecordBuilder<SensorData> {

    /** Unique identifier of the sensor */
    private java.lang.CharSequence sensor_id;
    /** Epoch time in milliseconds (UTC) */
    private long timestamp;
    /** Recorded temperature */
    private double temperature;
    /** Unit of measurement (e.g., Celsius) */
    private java.lang.CharSequence unit;
    /** Sensor location metadata (name/code) */
    private java.lang.CharSequence location;
    /** Geolocation latitude (if available) */
    private java.lang.Float latitude;
    /** Geolocation longitude (if available) */
    private java.lang.Float longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(SensorData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing SensorData instance
     * @param other The existing instance to copy.
     */
    private Builder(SensorData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unit)) {
        this.unit = data().deepCopy(fields()[3].schema(), other.unit);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * Unique identifier of the sensor
      * @return The value.
      */
    public java.lang.CharSequence getSensorId() {
      return sensor_id;
    }


    /**
      * Sets the value of the 'sensor_id' field.
      * Unique identifier of the sensor
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public SensorData.Builder setSensorId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sensor_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * Unique identifier of the sensor
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * Unique identifier of the sensor
      * @return This builder.
      */
    public SensorData.Builder clearSensorId() {
      sensor_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Epoch time in milliseconds (UTC)
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Epoch time in milliseconds (UTC)
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public SensorData.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Epoch time in milliseconds (UTC)
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Epoch time in milliseconds (UTC)
      * @return This builder.
      */
    public SensorData.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * Recorded temperature
      * @return The value.
      */
    public double getTemperature() {
      return temperature;
    }


    /**
      * Sets the value of the 'temperature' field.
      * Recorded temperature
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public SensorData.Builder setTemperature(double value) {
      validate(fields()[2], value);
      this.temperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * Recorded temperature
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'temperature' field.
      * Recorded temperature
      * @return This builder.
      */
    public SensorData.Builder clearTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * Unit of measurement (e.g., Celsius)
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * Unit of measurement (e.g., Celsius)
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public SensorData.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.unit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * Unit of measurement (e.g., Celsius)
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'unit' field.
      * Unit of measurement (e.g., Celsius)
      * @return This builder.
      */
    public SensorData.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * Sensor location metadata (name/code)
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * Sensor location metadata (name/code)
      * @param value The value of 'location'.
      * @return This builder.
      */
    public SensorData.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.location = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * Sensor location metadata (name/code)
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'location' field.
      * Sensor location metadata (name/code)
      * @return This builder.
      */
    public SensorData.Builder clearLocation() {
      location = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * Geolocation latitude (if available)
      * @return The value.
      */
    public java.lang.Float getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * Geolocation latitude (if available)
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public SensorData.Builder setLatitude(java.lang.Float value) {
      validate(fields()[5], value);
      this.latitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * Geolocation latitude (if available)
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'latitude' field.
      * Geolocation latitude (if available)
      * @return This builder.
      */
    public SensorData.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * Geolocation longitude (if available)
      * @return The value.
      */
    public java.lang.Float getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * Geolocation longitude (if available)
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public SensorData.Builder setLongitude(java.lang.Float value) {
      validate(fields()[6], value);
      this.longitude = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * Geolocation longitude (if available)
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'longitude' field.
      * Geolocation longitude (if available)
      * @return This builder.
      */
    public SensorData.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensorData build() {
      try {
        SensorData record = new SensorData();
        record.sensor_id = fieldSetFlags()[0] ? this.sensor_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.temperature = fieldSetFlags()[2] ? this.temperature : (java.lang.Double) defaultValue(fields()[2]);
        record.unit = fieldSetFlags()[3] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.location = fieldSetFlags()[4] ? this.location : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.latitude = fieldSetFlags()[5] ? this.latitude : (java.lang.Float) defaultValue(fields()[5]);
        record.longitude = fieldSetFlags()[6] ? this.longitude : (java.lang.Float) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensorData>
    WRITER$ = (org.apache.avro.io.DatumWriter<SensorData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensorData>
    READER$ = (org.apache.avro.io.DatumReader<SensorData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensor_id);

    out.writeLong(this.timestamp);

    out.writeDouble(this.temperature);

    out.writeString(this.unit);

    if (this.location == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.location);
    }

    if (this.latitude == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.latitude);
    }

    if (this.longitude == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.longitude);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);

      this.timestamp = in.readLong();

      this.temperature = in.readDouble();

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.location = null;
      } else {
        this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.latitude = null;
      } else {
        this.latitude = in.readFloat();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.longitude = null;
      } else {
        this.longitude = in.readFloat();
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensor_id = in.readString(this.sensor_id instanceof Utf8 ? (Utf8)this.sensor_id : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.temperature = in.readDouble();
          break;

        case 3:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.location = null;
          } else {
            this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.latitude = null;
          } else {
            this.latitude = in.readFloat();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.longitude = null;
          } else {
            this.longitude = in.readFloat();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










